### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by krisbros** [patrickmoffitt/Adafruit-Feather-M0-Motion-Camera#3]
Hello, 

I am not a pro at electronics but i do belive that this camera need a wifi connection to send the pictures to Adafruit webpage? Since you have mounted the camera in your garden, and there it is wifi connection available. I want to build this camera and place it in the forest where there is no wifi connection at all. Maybe rather go for a micro sd card in the assembly, and how difficult is that(programming)? Im a new beginner at programming too, 
Thanks for the project by the way, whery interesting. I want to do this because I want to learn about programming / electronics and I also need a wildlife camera.

Regards
Kristian

**Comment by patrickmoffitt** [comment]
Hi Kristian,
Thanks for your interest in this project. 

You are correct about the need for WiFi. The [microcontroller used in this project](https://www.adafruit.com/product/3010) includes the ATWINC1500 WiFi radio. To save the pictures to an SD card instead you could use [this variation](https://www.adafruit.com/product/2796) of the same line. You can find tutorials and sample code for the SD card functions on the Adafruit website.

Cheers,
Patrick Moffitt
